version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: ay_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    ports:
      - "5454:5432"  # Map PostgreSQL to port 5454 on the host
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - directus-net

  directus:
    image: directus/directus:latest
    container_name: ay_directus
    environment:
      - DB_CLIENT=pg
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=testdb        # Correct environment variable name
      - DB_USER=root
      - DB_PASSWORD=password
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=adminpassword
      - ADMIN_ROLE=admin
    ports:
      - "8080:8055"  # Expose Directus on port 8080 of the host
    volumes:
      - directus-data:/var/directus-data  # Volume for persisting Directus data
    depends_on:
      - postgres
    networks:
      - directus-net

  swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: ay_swagger
    environment:
      - SWAGGER_JSON=/swagger/swagger.json
    ports:
      - "8090:8080"  # Swagger UI accessible on port 8090 of the host
    volumes:
      - ./swagger:/swagger:ro  # Mount a local directory for the Swagger JSON file
    depends_on:
      - directus
    networks:
      - directus-net

volumes:
  postgres-data:
  directus-data:

networks:
  directus-net:
    driver: bridge
